### PR TITLE
CI tester 2

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/8/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/9/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/10/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/11/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/12/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/13/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/14/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/15/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>UNKNOWN</b> (click for details)</summary>

**Note:** the logs will be deleted after 25-Jul-2019

Log file | Status
-- | --
[build_lib.log](https://gist.githubusercontent.com/mellanox-github/965de9271526e143d9106f511f93d243/raw/d32a48f448801a8d4fdae0b5e588776ffe16cda1/build_lib.log) | :question: UNKNOWN
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/965de9271526e143d9106f511f93d243/raw/30df4f3246f4a6cfa3ea926e8c20f8da42a1fb8a/run_nccl_test.log) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 25-Jul-2019

Log file | Status
-- | --
[build_lib.log](https://gist.githubusercontent.com/mellanox-github/820a5e50443f626e56aa3baa5e257c36/raw/7cad9ada49a3eda5fffcfedea4dc8de703a4f2fb/build_lib.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/820a5e50443f626e56aa3baa5e257c36/raw/93873f82fc805480d685bb011470775cc06e0ba4/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>FAIL</b> (click for details)</summary>

**Note:** the logs will be deleted after 25-Jul-2019

Log file | Status
-- | --
[build_lib.log](https://gist.githubusercontent.com/mellanox-github/08ff83dcd2a4da798d461c3087d24645/raw/38c4e50b8ddeae2e201a3123ada2e348a34dc7d2/build_lib.log) | :x: FAIL
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/08ff83dcd2a4da798d461c3087d24645/raw/93873f82fc805480d685bb011470775cc06e0ba4/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Log file | Status
-- | --

**Comment by mellanox-github** [comment]
Test PASSed.

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 31-Jul-2019

Log file | Status
-- | --
[build_lib.log](https://gist.githubusercontent.com/mellanox-github/a4cfecdbaf1ba29d1ade3ffa0e72601f/raw/c35edb656c8f30c6acd00611242e9a5df43e81ec/build_lib.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/a4cfecdbaf1ba29d1ade3ffa0e72601f/raw/67ae737ef81b6ce8e3fd977cb0d16ae43a2a99f2/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 01-Aug-2019

Log file | Status
-- | --
[build_lib.log](https://gist.githubusercontent.com/mellanox-github/3b8fe6feac8c57b32761311ee8b3ab99/raw/11d13c24a174114617b749ff80487180cdeb4615/build_lib.log) | :heavy_check_mark: PASS
[run_nccl_test.log](https://gist.githubusercontent.com/mellanox-github/3b8fe6feac8c57b32761311ee8b3ab99/raw/cd35a862602be530873eaa5df26fe21a1b5806b9/run_nccl_test.log) | :heavy_check_mark: PASS

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 07-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Comment by artemry-nv** [comment]
bot:mlx:test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI status: <b>PASS</b#  > (click for details)</summary>

**Note:** the logs will be deleted after 08-Aug-2019

Log file | Status
-- | --

**Pull request closed without merging**
