### PR TITLE
CI tester

### PR DESCRIPTION
**Pull request by artemry-nv**

### CODE REVIEW

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/2/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/3/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/4/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
see http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/5/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/6/ for details (Mellanox internal link).

**Comment by artemry-nv** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/_ML_DevOps_team/job/ml-tf-fork-pr/7/ for details (Mellanox internal link).

**Pull request closed without merging**
